server:
  port: 9090
  error:
    include-message: always

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
    driver: org.postgresql.Driver

  sql:
    init:
      platform: postgres

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html